// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PmTool.Api.Models;

#nullable disable

namespace PmTool.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323095956_ProjectWorkspaceData")]
    partial class ProjectWorkspaceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("PmTool.Api.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("PmTool.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Communication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextMilestone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StakeholdersCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessMetric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologiesCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BudgetSpent = 126000m,
                            BudgetTotal = 180000m,
                            Communication = "Wochenstatus montags, Team-Sync mittwochs, Review freitags.",
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6718),
                            Customer = "RealCore Intern",
                            Description = "Zentrale Plattform fuer Projektsteuerung, Teamtransparenz und operative Zusammenarbeit.",
                            EndDate = new DateOnly(2026, 6, 30),
                            Name = "G-Share",
                            NextMilestone = "Projekt-Detailseite mit Team und Notizen live schalten",
                            Objective = "Ein zentrales Tool schaffen, in dem Projekte, Teams, Aufgaben und Notizen an einem Ort gepflegt werden.",
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProgressPercent = 72,
                            Scope = "Portfolio, Projekt-Detail, Ressourcen, Aufgabensteuerung, Notizen und Projektleiter-Workflows.",
                            StakeholdersCsv = "Management|Projektleitung|Delivery Team",
                            StartDate = new DateOnly(2026, 1, 15),
                            Status = "green",
                            SuccessMetric = "Projektteams koennen alle relevanten Projektinformationen in unter 2 Minuten finden und pflegen.",
                            TechnologiesCsv = "Next.js|TypeScript|Zustand|Tailwind CSS",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6719)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BudgetSpent = 76000m,
                            BudgetTotal = 140000m,
                            Communication = "Briefing Review dienstags, Prompt-Tuning donnerstags.",
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6737),
                            Customer = "RealCore Intern",
                            Description = "Tool fuer schnelle Management-Briefings mit Projektstatus, Risiken und To-dos aus einer Quelle.",
                            EndDate = new DateOnly(2026, 7, 15),
                            Name = "AI Briefing Tool",
                            NextMilestone = "Status- und Risikoantworten auf die neuen Projekte umstellen",
                            Objective = "Management-Briefings fuer Projekte automatisiert, kompakt und nachvollziehbar bereitstellen.",
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProgressPercent = 48,
                            Scope = "KI-Assistenz, Projektabfragen, Priorisierung von Risiken und Management-Zusammenfassungen.",
                            StakeholdersCsv = "Management|Sales|Projektleitung",
                            StartDate = new DateOnly(2026, 2, 1),
                            Status = "yellow",
                            SuccessMetric = "Ein Briefing fuer ein Projekt kann in unter 30 Sekunden erstellt werden.",
                            TechnologiesCsv = "Next.js|TypeScript|LLM Integration|Framer Motion",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6737)
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectLeadTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLeadTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19191919-1919-1919-1919-191919191919"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6860),
                            Description = "Budget, Fortschritt und Risiken fuer den Wochenbericht aktualisieren.",
                            DueDate = new DateOnly(2026, 3, 25),
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "in_progress",
                            Title = "Wochenstatus vorbereiten",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6861)
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6864),
                            Description = "Termin fuer Review der Projekt-Detailseiten festlegen.",
                            DueDate = new DateOnly(2026, 3, 29),
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "todo",
                            Title = "Abnahme mit Stakeholdern planen",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6865)
                        },
                        new
                        {
                            Id = new Guid("21212121-2121-2121-2121-212121212121"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6867),
                            Description = "Offene Scope-Fragen in den Projektnotizen festhalten.",
                            DueDate = new DateOnly(2026, 3, 22),
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "done",
                            Title = "Offene Entscheidungen dokumentieren",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6868)
                        },
                        new
                        {
                            Id = new Guid("22222221-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6871),
                            Description = "Formulierung fuer Status- und Risikoantworten finalisieren.",
                            DueDate = new DateOnly(2026, 3, 26),
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Status = "todo",
                            Title = "Prompt-Vorlagen abstimmen",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6871)
                        },
                        new
                        {
                            Id = new Guid("23232323-2323-2323-2323-232323232323"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6877),
                            Description = "Feedback fuer die erste Briefing-Version einholen.",
                            DueDate = new DateOnly(2026, 3, 30),
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Status = "in_progress",
                            Title = "Testbriefing mit Management teilen",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6877)
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            AuthorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Projektstruktur, Rollen und erste Prioritaeten mit dem Team abgestimmt.",
                            CreatedAt = new DateTime(2026, 2, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Kickoff Ergebnis",
                            UpdatedAt = new DateTime(2026, 2, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("17171717-1717-1717-1717-171717171717"),
                            AuthorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Projektleiter wollen Teammitglieder direkt am Projekt sehen und Notizen im Projekt pflegen.",
                            CreatedAt = new DateTime(2026, 3, 18, 13, 30, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Nutzerfeedback",
                            UpdatedAt = new DateTime(2026, 3, 18, 13, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            AuthorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Zunaechst nur zwei Projekte unterstuetzen, um das Briefing konsistent zu halten.",
                            CreatedAt = new DateTime(2026, 3, 10, 10, 15, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Scope Fokus",
                            UpdatedAt = new DateTime(2026, 3, 10, 10, 15, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PmTool.Api.Models.ResourceAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AllocatedHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("ResourceAllocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AllocatedHours = 34,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6768),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectRole = "Projektleiter",
                            Responsibility = "Steuerung, Stakeholder-Management, Priorisierung",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6768),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AllocatedHours = 30,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6775),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectRole = "Product Owner",
                            Responsibility = "Anforderungen, Backlog, Fachseite",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6775),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AllocatedHours = 36,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6777),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectRole = "Frontend Developer",
                            Responsibility = "Dashboard, Projektseiten, UX-Umsetzung",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6778),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            AllocatedHours = 32,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6780),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectRole = "Backend Developer",
                            Responsibility = "APIs, Datenmodell, Berechtigungen",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6780),
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            AllocatedHours = 28,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6783),
                            ProjectId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProjectRole = "QA Engineer",
                            Responsibility = "Testfaelle, Regression, Abnahme",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6783),
                            UserId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            AllocatedHours = 18,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6785),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProjectRole = "Projektleiter",
                            Responsibility = "Roadmap, Stakeholder, Freigaben",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6786),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            AllocatedHours = 38,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6789),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProjectRole = "AI Engineer",
                            Responsibility = "Prompting, Auswertung, Response-Logik",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6789),
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            AllocatedHours = 20,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6791),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProjectRole = "Frontend Developer",
                            Responsibility = "Chat-UI und Briefing-Darstellung",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6792),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            AllocatedHours = 24,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6796),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProjectRole = "UX Designer",
                            Responsibility = "Informationsarchitektur und Lesbarkeit",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6797),
                            UserId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("PmTool.Api.Models.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("PmTool.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6468),
                            IsActive = true,
                            Name = "RealCore",
                            Slug = "realcore",
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6472)
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6600),
                            DisplayName = "Berk Can Atesoglu",
                            Email = "berkcan@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "Projektleiter",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6601)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6614),
                            DisplayName = "Selin Kaya",
                            Email = "selin@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "Product Owner",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6614)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6616),
                            DisplayName = "Emre Yilmaz",
                            Email = "emre@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "Frontend Developer",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6617)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6619),
                            DisplayName = "Mira Hoffmann",
                            Email = "mira@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "Backend Developer",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6619)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6621),
                            DisplayName = "Can Demir",
                            Email = "can@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "AI Engineer",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6621)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6623),
                            DisplayName = "Lena Schmidt",
                            Email = "lena@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "UX Designer",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6624)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6626),
                            DisplayName = "Jonas Weber",
                            Email = "jonas@realcore.de",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "QA Engineer",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 23, 9, 59, 54, 364, DateTimeKind.Utc).AddTicks(6626)
                        });
                });

            modelBuilder.Entity("PmTool.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId");

                    b.HasOne("PmTool.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PmTool.Api.Models.Project", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.Tenant", null)
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectLeadTask", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("LeadTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectNote", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectTask", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PmTool.Api.Models.ResourceAllocation", b =>
                {
                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("TeamAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PmTool.Api.Models.Risk", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PmTool.Api.Models.TaskComment", b =>
                {
                    b.HasOne("PmTool.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PmTool.Api.Models.ProjectTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PmTool.Api.Models.User", b =>
                {
                    b.HasOne("PmTool.Api.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PmTool.Api.Models.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("LeadTasks");

                    b.Navigation("Notes");

                    b.Navigation("Risks");

                    b.Navigation("Tasks");

                    b.Navigation("TeamAssignments");
                });

            modelBuilder.Entity("PmTool.Api.Models.ProjectTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PmTool.Api.Models.Tenant", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
